const MONGO_URL = process.env.MONGO_URL
ADMIN_JWT_SECRET = process.env.ADMIN_JWT_SECRET
USER_JWT_SECRET = process.env.USER_JWT_SECRET

module.exports = {
    MONGO_URL : MONGO_URL,
    ADMIN_JWT_SECRET : ADMIN_JWT_SECRET,
    USER_JWT_SECRET : process.env.USER_JWT_SECRET
}